### ISSUE TITLE
Adding a flexible axes plot

### ISSUE THREAD

**Issue by jmackereth** [jmackereth/tess-cvz-app#2]
We want to add a panel with a plot that has axes that can be changed to look at different interesting properties. Ideally this should come with some suggested configurations that are interesting. Not sure if it needs to have a colour option (i.e. colour points by parameters)

Suggested properties:
- [Fe/H]
- [a/Fe]
- log(g)
- Teff
- Age
- Mass
- Velocity? Orbital parameters?

**Comment by EmmaWillett** [comment]
Sorry, I can't find a way to assign myself to this task, but I'm having a go at it! So far I'm having a problem reading the .npy file, so I'll play around with making the plot in a separate notebook and hopefully we can integrate it later

**Comment by jmackereth** [comment]
Hey Emma - best thing to do: 
 - fork this repo (do this in the browser)
 - then `git clone` your fork
 - then do `git branch <name-of-new-branch>` - something like `flexible-axes` would be fine for the name
 - then you can switch to that branch of your fork in the browser and open a pull request which references this issue, once the pull request is open, it will move the card to 'in progress' in the project page. You can keep notes here or in the Pull request page.
